### ISSUE TITLE
Why emojis and not words?

### ISSUE THREAD

**Issue by alescode** [argentlabs/emoji-hash#1]
Emojis are cute, but if the recommended secondary medium of communication is going to be a phone call, words are more easily recognizable and pronounceable.

**Comment by th3m477** [comment]
Either can be acceptable, however emojis are universal and cross language barriers. When using secondary medium you will be talking to people you know, and thus can describe emojis in your own language/dialogue.

Note we did have to make sure we only use common emojis that are similar on both iOS and Android, to minimise any potential confusion between graphical differences.
